---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "submer-pod-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "submer-pod-exporter.name" . }}"
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "submer-pod-exporter.name" . }}"
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
