{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "submer-pod-exporter.name" $ }}-service-monitor
  {{- if $.Values.serviceMonitor.namespace }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "submer-pod-exporter.name" . }}"
{{- if .Values.serviceMonitor.labels }}
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
{{- end }}
spec:
  endpoints:
  - port: http
    path: {{ $.Values.serviceMonitor.path }}
    {{- if $.Values.serviceMonitor.interval }}
    interval: {{ $.Values.serviceMonitor.interval }}
    {{- end }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    {{- if or .relabelings }}
    relabelings: {{ toYaml $.Values.serviceMonitor.relabelings | nindent 8 }}
    {{- end }}
  jobLabel: "{{ $.Release.Name }}"
  selector:
    matchLabels:
      app: "{{ template "submer-pod-exporter.name" . }}"
{{- end }}
